Support `ui.open` with new tab
zauberzeug/nicegui pull request #1243
Opened 2023-07-24 08:45 UTC by falkoschindler

This PR implements the feature request #960, adding an optional parameter `new_tab` to `ui.open`:

```py
@ui.page('/test')
def test():
    ui.label('Hello world!')

ui.button('Open page', on_click=lambda: ui.open('/test'))
ui.button('Open page', on_click=lambda: ui.open('/test', new_tab=True))
```

2023-07-25 03:32 UTC, rodja requested changes
@falkoschindler could you add a test?

2023-07-26 11:24 UTC, falkoschindler commented
@rodja Good idea. `ui.open` hasn't been tested at all. Commit [3caac4c](https://github.com/zauberzeug/nicegui/pull/1243/commits/3caac4c2bcaf5c02c81003133153d565e6414fff) adds tests for both cases.

2023-07-26 14:36 UTC, rodja approved these changes
Great!

2023-07-26 15:17 UTC, merged

2023-08-17 18:19 UTC, v479038280 commented
> This PR implements the feature request #960, adding an optional parameter `new_tab` to `ui.open`:
> 
> ```python
> @ui.page('/test')
> def test():
>     ui.label('Hello world!')
> 
> ui.button('Open page', on_click=lambda: ui.open('/test'))
> ui.button('Open page', on_click=lambda: ui.open('/test', new_tab=True))
> ```

could the new_tab be a ui.tab()?

2023-08-17 20:15 UTC, falkoschindler commented
@v479038280 No.

2023-08-18 05:21 UTC, v479038280 commented
> 

That's a suggestion