PR: add seek/play/pause to audio/video
zauberzeug/nicegui pull request #1672
Opened 2023-09-23 17:18 UTC by wgong

per https://github.com/zauberzeug/nicegui/discussions/1636

2023-09-25 07:48 UTC, falkoschindler requested changes
Thanks for this PR, @wgong! I really like these new features.
I just have minor remarks that we should address before merging into main.

2023-09-25 07:48 UTC, falkoschindler commented on nicegui/elements/video.js
Is there a reason you didn't add a seek method for `ui.video`?

2023-09-25 07:48 UTC, falkoschindler commented on examples/audio_video/main.py
I would prefer to move this example into demos for `ui.audo` and `ui.video` (see audio_documentation.py and video_documentation.py). Since they are rather short, I guess there's no need to hide them in the examples folder.

2023-09-25 07:48 UTC, falkoschindler commented on .gitignore
This change seems unnecessary.

2023-09-25 07:48 UTC, falkoschindler commented on nicegui/elements/video.py
One-line docstrings can be placed in a single line, see https://peps.python.org/pep-0257/#one-line-docstrings.

2023-09-25 07:48 UTC, falkoschindler commented on nicegui/elements/audio.py
One-line docstrings can be placed in a single line, see https://peps.python.org/pep-0257/#one-line-docstrings.

2023-10-02 12:30 UTC, falkoschindler commented
@wgong Are you still working on this pull request? Would be great to have it ready for the next release 1.3.16. 🙂

2023-10-02 15:14 UTC, wgong commented
Thanks, will incorporate your feedback tonight

On Mon, Oct 2, 2023, 8:30 AM Falko Schindler ***@***.***>
wrote:

> @wgong <https://github.com/wgong> Are you still working on this pull
> request? Would be great to have it ready for the next release 1.3.16. 🙂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zauberzeug/nicegui/pull/1672#issuecomment-1742927741>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACQRSHVZRE3FAGVFJHVR73X5KXWJAVCNFSM6AAAAAA5EKLLT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBSHEZDONZUGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-02 21:41 UTC, closed without merging

2023-10-02 21:44 UTC, wgong commented on nicegui/elements/video.js
video.js already has seek() 
https://github.com/zauberzeug/nicegui/blob/1010535befc70233394dd3dc86a80f08248e6c01/nicegui/elements/video.js#L24

2023-10-02 22:20 UTC, wgong commented on .gitignore
removed

2023-10-02 22:21 UTC, wgong commented on nicegui/elements/video.py
done

2023-10-02 22:21 UTC, wgong commented on nicegui/elements/audio.py
done

2023-10-02 22:22 UTC, wgong commented on examples/audio_video/main.py
How do I run website locally? I need to test my changes

2023-10-03 06:56 UTC, falkoschindler commented on nicegui/elements/video.js
Yes, but video.py doesn't. But it's hard to tell now, since you somehow removed the code from this PR.

2023-10-03 06:57 UTC, falkoschindler commented on examples/audio_video/main.py
Just run `main.py`.

2023-10-03 06:59 UTC, falkoschindler commented
I'm a bit confused since you somehow removed all changes from this PR and closed it. So I assume you will open a new one.
Usually you can keep working on a pull request until it's finished and gets merged.

2023-10-03 16:20 UTC, wgong commented
I have not created PR yet, recreated changes to support audio/video seek.
Like to know how run website locally to test demo code since you suggested
to remove examples

On Tue, Oct 3, 2023, 2:59 AM Falko Schindler ***@***.***>
wrote:

> I'm a bit confused since you somehow removed all changes from this PR and
> closed it. So I assume you will open a new one.
> Usually you can keep working on a pull request until it's finished and
> gets merged.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zauberzeug/nicegui/pull/1672#issuecomment-1744323102>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACQRSG7FS5LPOB7V3UP2SLX5OZWNAVCNFSM6AAAAAA5EKLLT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBUGMZDGMJQGI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-10-04 08:54 UTC, falkoschindler commented
Just run `main.py`.