Added color and icon modules.
zauberzeug/nicegui pull request #2537
Opened 2024-02-12 02:35 UTC by ZeroCool940711

This PR adds color and icon modules for easy access to some colors and icons that can be found by the IDE autocomplete and code suggestions as mentioned in [this discord conversation](https://discord.com/channels/1089836369431498784/1089836370043883654/1205303194192715846). These colors and icons can be used in the following way:
```python
from nicegui import color, icon, ui

ui.button("NiceGUI", color=color.GREEN, icon=icon.THUMB_UP, on_click=lambda: ui.icon(icon.FACE))

ui.run(native=True, reload=True)
```

As an extra, I also added a way to set the `APP_ID` (for the task manager) and `APP_ICON` (taskbar and app favicon in native mode) on the Windows platform. By default, the `APP_ID` will be set as `APP_ID = f"nicegui.zauberzeug.version.{__version__}"` and the NiceGUI favicon is used from the `static` folder. They both can be changed in the following way:
```python
from nicegui import icon
icon.APP_ID = "my_app_id.username_or_company_name.version.app_version"
icon.set_app_icon("icon.ico")
```
The path can be relative to the working directory or an absolute path.
![image](https://github.com/zauberzeug/nicegui/assets/5977640/21867781-f4e9-4c22-aff4-8d74cfe63863)

Note: Sometimes the icon will not show up in the taskbar until the app does a reload at lest once. We might need to find a way to fix this behavior or force a reload when we launch our app so the icon is shown correctly.

2024-02-12 03:30 UTC, rodja commented
Thanks for the PR @ZeroCool940711! I feel that `APP_ID` and `APP_ICON` should not be located in `icon.py` but rather in `app.native`. They are only relevant when using Native Mode. And these additions should be a separate pull request because they are so very distinct from the color and icon auto-complete helpers you propose here.

2024-02-12 03:33 UTC, ZeroCool940711 commented
> Thanks for the PR @ZeroCool940711! I feel that `APP_ID` and `APP_ICON` should not be located in `icon.py` but rather in `app.native`. They are only relevant when using Native Mode. And these additions should be a separate pull request because they are so very distinct from the color and icon auto-complete helpers you propose here.

I understand. I will remove the `APP_ID` and `APP_ICON` code for now and see how I can implement them in the place you mentioned. Give me a minute to push a commit to correct that.

2024-02-12 03:36 UTC, ZeroCool940711 commented
@rodja Done. I pushed a commit to remove the `APP_ID` and `APP_ICON` from the `icons.py`.

2024-02-12 03:39 UTC, rodja approved these changes

2024-02-12 17:23 UTC, ZeroCool940711 commented
> 1. How did you generate these files? Since we need to maintain and update them whenever we include a new version of the icons font, we'd ideally have a generator script we can simply run again.

Both the [colors.py](https://github.com/flet-dev/flet/blob/main/sdk/python/packages/flet-core/src/flet_core/colors.py) and [icons.py](https://github.com/flet-dev/flet/blob/main/sdk/python/packages/flet-core/src/flet_core/icons.py) come from the Flet library, I just copied them from there.

> 2. Icons with suffixes like `_SHARP` don't seem to work, e.g. `ui.icon(icon.YOUTUBE_SEARCHED_FOR_SHARP)`.
> 3. What is `color.ON_PRIMARY` supposed to be? I don't know color identifiers with such a prefix and they don't seem to be working. Same for shades of white like `white10`.
> 4. You don't cover Quasar and CSS colors, right? Why not?

Some colors and icons might not work since they are directly taken from Flet and it is based on flutter icons and colors dart files. We should find a way to get these colors and icons automatically from the libraries NiceGUI uses and use CI to generate these files which is why I tried to keep them as individual files that can be modified without affecting the rest of the codebase, I mentioned that on the discord conversation but I forgot to mention that here on the PR.

> 5. To make `color` and `icon` part of the public API, we should add it to `nicegui/__init__.py`.
> 6. There's already an implementation in `color_elements.py` checking for Quasar and Tailwind colors. The latter is done using the `BackgroundColor` literal from the `tailwind_types` module. Maybe this can be useful for generating `color.py`, but I'm not sure.

I tried to avoid modifying anything other than the files I added since some tests are failing locally so I'm not able to make sure I don't break something else, even on a clean clone of the repo on my setup and I need to look into that first, I initially just shared both files on discord for those that wanted to use them as extra utils on their project but it was suggested that I should do a PR with them so I tried to find a way to incorporate them as part of NiceGUI itself which is what this PR is about. The added colors and icons works in the most part and it's meant to be improved later on and modified to match what NiceGUI needs, this is more like a proof of concept on an alternative way we could implement colors and icons and have them accessible for easy discovery by the IDE autocomplete, it is also meant to reduce the learning curve of using NiceGUI which is related to the discussion on #2538 . I will look into how we can get the colors and icons from Quasar, CSS, HTML and Tailwind and improve this PR, I'm open to suggestions on how to do that.

2024-02-12 22:28 UTC, ZeroCool940711 commented
>To make color and icon part of the public API, we should add it to nicegui/__init__.py.

I added both of them to the `nicegui/__init__.py` and will look into finding a way to automate adding new colors and icons, let me know what else you recommend I do.

2024-02-13 01:03 UTC, ZeroCool940711 commented
just a little update, I found [this file](https://raw.githubusercontent.com/tailwindlabs/tailwindcss/master/src/public/colors.js) from the Tailwind repo which we can use to get the colors for Tailwind and keep them up-to-date. I started to work on script that we can use. After Im done with tailwind I will move to the rest of the colors we need and see how many of them I can get.

2024-02-13 09:35 UTC, ZeroCool940711 commented
Sorry about the forced pushes, I was fixing the commit message on the `publish.yml` to reflect the new files and had a few typos that I noticed only after pushing and reading the `File Changed` tab here, it happened a few times 😓. 

I think this PR is ready for review now since I think I have addressed all the issues it had. I still think we could improve it with more icons and colors but I think this is enough for now, we can always come back to this and add more stuff if needed.

2024-02-19 20:14 UTC, falkoschindler requested changes
Hi @ZeroCool940711, here are my thoughts after reviewing your updated pull request:

- [ ] We should remove the GitHub workflow for now. Since `color.py` and `icon.py` need to stay in sync with the Tailwind and Quasar versions managed via npm.py, we shouldn't pull new icons or colors if we don't update the libraries as well. And because updates could cause breaking changes, we only do that manually before major releases.

- [ ] There are many manually managed icons in `number_words`. I'm not quite sure what to do with them, but the list of more than 100 special cases seems rather fragile. A `_` prefix could be a generic alternative, but could mislead linters because it usually denotes private attributes.

- [ ] There are many duplicate icons. This is probably related to my next point.

- [ ] What about different families (outlined, symbols, ...)? How could an API look like for different families? `icon.sharp.HOME`, `icon.SHARP_HOME`, `icon.HOME_SHARP`, or something different? The default "filled" icon could still be accessed like `icon.HOME`. What do you think? We should probably agree on an API first before updating the generator script.

- [x] You're downloading the icons via HTTP. We should switch to HTTPS.

- [ ] There are many manually managed colors in `quasar_colors`. I understand colors like `PRIMARY`, `INFO` and so on. But where do colors like `ICE_DUST` come from?

- [ ] Your basically re-implementing `QUASAR_COLORS` and `TAILWIND_COLORS` from color_element.py. We should either use those directly or use the colors from color.py there.

- [ ] Can we add support for CSS colors? It seems kind of misleading if the `color` namespace doesn't include `SteelBlue`, even though it is a valid color in NiceGUI.

- [ ] I think colors like `AMBER100` should map to `amber-100`, not the hex value `#...`. Currently some of your colors map to class names, others to hex values, which makes them unusable in `.style()` or `.classes()` calls.

- [ ] Should we distinguish color groups? This might improve clarity and explains where the color names come from: `color.css.RED`, `color.tw.RED_100`, `color.q.RED_1`. Additionally we could provide aliases `color.tailwind` and `color.quasar`.

2024-02-20 05:22 UTC, ZeroCool940711 commented
> * [ ]  We should remove the GitHub workflow for now. Since `color.py` and `icon.py` need to stay in sync with the Tailwind and Quasar versions managed via npm.py, we shouldn't pull new icons or colors if we don't update the libraries as well. And because updates could cause breaking changes, we only do that manually before major releases.

I've gone ahead and removed those from the workflow, I still think that it would be better to have this automated, if breaking changes are a concern we could add a test for checking that all the colors and icons are valid and working properly and run those tests before release.

> * [ ]  There are many manually managed icons in `number_words`. I'm not quite sure what to do with them, but the list of more than 100 special cases seems rather fragile. A `_` prefix could be a generic alternative, but could mislead linters because it usually denotes private attributes.

The `number_words` list is actually a pain for me, I tried to find a solution to automatically convert numbers to words since python does not allow variables to start with a number but I couldn't find a solution, the best I could do was using the `number_words` list as it is now, I will gladly change that if we can find a better way to fix that issue, I'm not happy either with that list but I didn't have a choice, was either that or removing those icons from the `icon.py` file completely.

> * [ ]  There are many duplicate icons. This is probably related to my next point.

I have added some code to remove all the duplicates and also to sort the icons, I was doing this with the colors but seems like I forgot to add it to the icons as well.

> * [ ]  What about different families (outlined, symbols, ...)? How could an API look like for different families? `icon.sharp.HOME`, `icon.SHARP_HOME`, `icon.HOME_SHARP`, or something different? The default "filled" icon could still be accessed like `icon.HOME`. What do you think? We should probably agree on an API first before updating the generator script.

The icons are taken from [this repo](https://github.com/twbs/icons/tree/main/icons), I couldn't find any other source with more icons that would work with NiceGUI since I'm not 100% what it supports and what it doesn't but if you have any links I can use I will add them, the more icons we have the better. I also plan to add a way to see all the icons we have either in the docs or add an element for selecting icons, that would be an interesting element that I think I can do combining already existing elements in NiceGUI.

> * [ ]  You're downloading the icons via HTTP. We should switch to HTTPS.

I've fixed this, the icons should be downloaded now from https instead of http.

> * [ ]  There are many manually managed colors in `quasar_colors`. I understand colors like `PRIMARY`, `INFO` and so on. But where do colors like `ICE_DUST` come from?

The `ICE_DUST` and a few others come [from here](https://github.com/quasarframework/quasar/blob/ee59d24f2955bba368f3f75712e1a44ea4222f6d/docs/src/css/quasar.variables.sass#L21), those are mostly variables that are repeated in many places but not have their value directly on the file we used to get the list of colors so we needed to add them manually for now, I'm planning to automatically get those later on.

> * [ ]  Your basically re-implementing `QUASAR_COLORS` and `TAILWIND_COLORS` from color_element.py. We should either use those directly or use the colors from color.py there.

Technically speaking, you are right, what I have been doing is re-implementing the `QUASAR_COLORS` and `TAILWIND_COLORS` in a way that is easier to access and discover. I would suggest we use them from the `color.py` file, this way we have everything in a single place and we can automatically update them instead of having things in different places. We should reference the colors from that file in any other place that they were used before, that would also help to make sure things work properly across the whole codebase.

> * [ ]  Can we add support for CSS colors? It seems kind of misleading if the `color` namespace doesn't include `SteelBlue`, even though it is a valid color in NiceGUI.

I want to add more colors and icons but as I said for the icons above I would need some links from where to get them and be sure what NiceGUI supports or not.

> * [ ]  I think colors like `AMBER100` should map to `amber-100`, not the hex value `#...`. Currently some of your colors map to class names, others to hex values, which makes them unusable in `.style()` or `.classes()` calls.

To give some answers to this I would need to explain a few things:
- names/variables for colors and icons are all in uppercase: The reason for this is simple, it's easy to distinguish them from other things in the code. If you see `something.SOMETHING` that means we are calling a variable that we are importing from another module/script and not a method or function which makes it easier to debug code when you have a big app with a lot of LOC.
- [Tailwind](https://raw.githubusercontent.com/tailwindlabs/tailwindcss/master/src/public/colors.js)/[Quasar](https://raw.githubusercontent.com/quasarframework/quasar/dev/ui/src/css/core/colors.sass) colors: Quasar colors have an underscore in their names while Tailwind colors don't. To directly answer your question, `AMBER100` refers to a Tailwind color while `amber-100` or `AMBER_100` would be a Quasar color.
- hex vs class names: As mentioned before, colors with hex values are for Tailwind colors while those with `class-names` are for Quasar colors.

> Should we distinguish color groups? This might improve clarity and explains where the color names come from: `color.css.RED`, `color.tw.RED_100`, `color.q.RED_1`. Additionally we could provide aliases `color.tailwind` and `color.quasar`.

I don't think having groups would be a good idea. The reason is that it would make finding a specific color difficult if you don't know where it should be or to what it belongs to. With everything inside `color.py` and it just being variables with values we can test different colors and find new ones to use even by accident, the IDE autocompletion/suggestion will show you the list of all the colors and filter them as you type giving you a list of all the colors you can use that match what you type, if you type "red" you get a list of all the colors with the word red in it, be from tailwind, quasar or css when we add them, so, it would make it easier to switch from one to another if you don't like them or they are not good for your use case. On the contrary, if we have groups like `color.css.RED`, etc, it would be hard to know where to look for when you have no idea if the color is from tailwind or quasar, it would make it so users will tend to stick with a single group since they would only go to `color.tw` directly and not experiment with other colors or they could even not know that they exist, specially if there is no documentation for them.

2024-02-20 06:09 UTC, rodja commented
I think it would be sufficient to stick with Quasar colors for auto-completion. Tailwind colors are accessable through `.tailwind` and css colors do not need auto-completion because they are in `.style` strings anyway.

2024-02-20 06:24 UTC, falkoschindler commented
@rodja Regarding CSS colors I have to disagree. They are not only used in `.style` strings:

```py
ui.icon('home', color='SteelBlue')
```

2024-02-20 06:47 UTC, ZeroCool940711 commented
> @rodja Regarding CSS colors I have to disagree. They are not only used in `.style` strings:
> 
> ```python
> ui.icon('home', color='SteelBlue')
> ```

That is one of the ways I mainly use the colors and icons introduced in this PR, in buttons and other elements that take a color or icon argument, it's much easier than the normal method, it is also, at least for me, to stick with a color scheme/palette.

2024-02-20 06:53 UTC, falkoschindler commented
For CSS we could simply use [webcolors](https://pypi.org/project/webcolors/). It's another dependency, but very lightweight. They define colors in https://github.com/ubernostrum/webcolors/blob/trunk/src/webcolors/constants.py based on current web standards.

2024-02-20 07:37 UTC, ZeroCool940711 commented
> For CSS we could simply use [webcolors](https://pypi.org/project/webcolors/). It's another dependency, but very lightweight. They define colors in [ubernostrum/webcolors@`trunk`/src/webcolors/constants.py](https://github.com/ubernostrum/webcolors/blob/trunk/src/webcolors/constants.py?rgh-link-date=2024-02-20T06%3A53%3A55Z) based on current web standards.

I added all the HTML4, CSS2, CSS21 and CSS3 colors from webcolors constants as well as webcolors as a dependency. Im not sure if I placed that dependency on the right place so, feel free to let me know where to put them if thats the wrong place.

2024-02-22 12:27 UTC, ZeroCool940711 commented
I noticed while working on an `IconPicker/IconInput` element for working with the icons that many of the icons are not centered for some reason, I first thought that they were missing but it seems like they are just not centered on the element using them, if you place them in a button for example they can be outside the button container/area, if they overlap with another button or element they seem to interact with that element when you click in them, like, you click in one button and it interacts with the other button as well because they overlap, I think that's weird and probably a bug somewhere. 
![image](https://github.com/zauberzeug/nicegui/assets/5977640/e85e5d86-d892-4718-8962-c3af75d6c2a6)
![image](https://github.com/zauberzeug/nicegui/assets/5977640/b0c657d5-51ef-4726-9221-2eb47620c21f)
In the first screenshot above, I had my mouse over the button with the red line under it but the one next to it was the one that was being selected and showing the tooltip for, the second image shows the actual button tooltip if I hover in the top right corner of it almost leaving the button area.

2024-02-22 19:37 UTC, rodja commented
@ZeroCool940711 could you share your test code?

2024-02-23 01:13 UTC, ZeroCool940711 commented
@rodja sorry I didn't answer before, just got up from bed. I had just started making a prototype for the element I would be working on so, the code is pretty basic but it should show you the issue I was talking about:
```python
from nicegui import icon, ui


@ui.page("/")
def index():
    with ui.card().style("max-width: 400px;"):
        ui.select(["Google Icons"], value="Google Icons")

        with ui.input(placeholder="Search icons..."):
            ui.icon("search").style(
                "position: absolute; right: 1rem; top: 50%; transform: translateY(-50%);"
            )

        with ui.row():
            icon_vars = vars(icon)
            icons = {k: icon_vars[k] for k in list(icon_vars.keys())[8:78]}
            for icon_name, icon_value in icons.items():
                ui.button(
                    icon=icon_value,
                    on_click=lambda e=icon_value: ui.clipboard.writeText(e),
                ).tooltip(icon_name)


if __name__ in {"__main__", "__mp_main__"}:
    ui.run(
        port=5000,
        native=True,
        reload=True,
        dark=True,
    )

```

2024-02-23 03:58 UTC, rodja commented
Well... my minimal reproduction is this:

```py
from nicegui import ui

ui.button(icon='action_key').classes('w-48')

ui.run()
```

Maybe our font file is not correct?

2024-02-23 04:23 UTC, rodja commented
It looks like the icon name `action_key` is simply not supported. Let's have a closer look at the json fetched from the google fonts api:

```json
{
      "name": "action_key",
      "version": 251,
      "popularity": 31,
      "codepoint": 62722,
      "unsupported_families": [
        "Material Icons",
        "Material Icons Outlined",
        "Material Icons Round",
        "Material Icons Sharp",
        "Material Icons Two Tone"
      ],
      "categories": [
        "UI actions"
      ],
      "tags": [
        "buttons",
        "circles",
        "computer",
        "device",
        "dots",
        "filter",
        "find",
        "glass",
        "grid",
        "hardware",
        "input",
        "keyboard",
        "keypad",
        "look",
        "magnify",
        "magnifying",
        "search",
        "see"
      ],
      "sizes_px": [
        20,
        24,
        40,
        48
      ]
    }
```

I think the `update_icons.py` script needs to evaluate the `unsupported_families` list.

2024-02-23 05:26 UTC, ZeroCool940711 commented
> I think the `update_icons.py` script needs to evaluate the `unsupported_families` list.

mmm, I'm not sure what to do, a lot of icons that are technically not supported do render properly and centered as they should. What do you recommend I do to make sure the icons list we get on `update_icons.py` works with NiceGUI?

2024-02-25 17:02 UTC, falkoschindler commented
This PR is getting pretty big and complex. Instead of trying to review and improve the existing implementation, I created PR #2613 and PR #2614 as an alternative approach. They are heavily inspired by the discussion on this thread, but cut some corners here and there. By splitting the problem into separate PRs, I hope to simplify the discussions and improve focus on each subject. Tests and documentation are still missing though.

2024-02-25 17:39 UTC, ZeroCool940711 commented
@falkoschindler For the colors PR I think that one is actually good and that was one of the things I was trying to do to fix this PR later on but the other PR, from what I can see on your icon PR you just completely ignored all the talks we had here about not doing some stuff in some way because it would have negative effects in how people use things, and you also ignored all the fixes that I had to break my head to do for things to be at the point where I got this PR to, then you went with the most basic copy/paste implementation you could do in an hour, for which your icon implementation PR still has all the issues of the original PR that I later fixed, from variable names starting with `_` to missing and broken icons as well as duplicates, I mean, even the tests are failing on your PR, and you improved nothing on it other than having a PR to your name with your own commit history instead of the original, that's the big difference? WoW.

2024-02-25 18:21 UTC, falkoschindler commented
Sorry, @ZeroCool940711, it wasn't my intention to just have a PR on my name. And I didn't copy&paste, but spent quite a while to re-implement these features. As mentioned on the PR for the icon module, I had something more elaborate in mind which didn't work.

Regarding your points of criticism:

- Which icons are broken or missing?
- Where do you see duplicates?
- The tests are a bit flaky. There's only one failure out of >1500 tests which is unrelated to the icon module.
- Yes, I argued against the leading underscore. But all other attempts seem too unintuitive, so that's my favorite compromise at the moment.

2024-04-08 09:50 UTC, closed without merging