Add min/max/step/prefix/suffix to ui.number
zauberzeug/nicegui pull request #790
Opened 2023-04-18 15:34 UTC by falkoschindler

Following the discussion #765 this PR extends the `ui.number` element with additional parameters.
On blur the value is sanitized using the min and max values as well as the format string - if given.

2023-04-18 15:42 UTC, rodja requested changes

2023-04-18 15:45 UTC, falkoschindler commented on tests/test_number.py
> +    screen.should_contain_input('10')
The value is already "5". After sending the key "6", the value is now "56", which is sanitized down to "10".

2023-04-18 15:54 UTC, rodja commented on tests/test_number.py
> +    screen.should_contain_input('10')
Ah, I understand. It just appends. Maybe we should type "600" to make it more clear that the value is capped to 10?

2023-04-18 19:57 UTC, falkoschindler commented on tests/test_number.py
> +    screen.should_contain_input('10')
Yes, we could do that. On the other hand the other number test using pi (3.1416) also only makes sense for _appending_ digits.

2023-04-19 02:55 UTC, rodja commented on tests/test_number.py
> +    screen.should_contain_input('10')
Ok. I'm convinced. We leave it as it is ;-)

2023-04-19 02:55 UTC, rodja approved these changes

2023-04-19 02:55 UTC, merged