Add sqlite CRUD example
zauberzeug/nicegui pull request #822
Opened 2023-04-23 21:23 UTC by godsarmy

This is a demo code almost same as https://www.youtube.com/watch?v=n2Z0pflkZQU but with a little bit improvement (such as better way to initialize sqlite file)

2023-04-24 04:46 UTC, rodja requested changes
Thanks for the example. A small database example was really missing. I made some comments throughout the code where you may want to improve it a little. But overall I think it will greatly help other users! Thanks again.

2023-04-24 04:46 UTC, rodja commented on examples/sqlite/main.py
> +        list_alldata.clear()
You could take advantage of [ui.refreshable](https://nicegui.io/documentation#refreshable_ui_functions) to simplify the code.

2023-04-24 04:46 UTC, rodja commented on examples/sqlite/main.py
> +    for row in res:
Maybe use list comprehension to simplify the construction of `result`?

2023-04-24 04:46 UTC, rodja commented on examples/sqlite/main.py
> +    get_id.text = data.default_slot.children[0].text
Grabbing the data from the UI is not super elegant. Maybe the example could benefit from an ORM like https://tortoise.github.io/?

2023-04-25 15:06 UTC, rodja commented
@godsarmy I would really like this to be part of the 1.2.10 release. Do you think you can make the adaptations until tomorrow?

2023-04-26 02:47 UTC, godsarmy commented
hi

I changed partial but i am super busy these days. I hope to complete all my
changes in this week.

Rodja Trappe ***@***.***> 于 2023年4月25日周二 11:06写道：

> @godsarmy <https://github.com/godsarmy> I would really like this to be
> part of the 1.2.10 release. Do you think you can make the adaptations until
> tomorrow?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zauberzeug/nicegui/pull/822#issuecomment-1521956972>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFTVZ5Q6MS5TJWCWWAVWZDXC7SANANCNFSM6AAAAAAXIY4NLM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-02 03:02 UTC, rodja requested changes
I've made a few small comments in the code. Additionally your example should be listed on the website. Use the example_link function below the ["In-depth examples" section heading](https://github.com/zauberzeug/nicegui/blob/8a86d2064f8f4464f3819ac5c6763a2cb2d0e990/main.py#L242). The title should match the example folder name when [snake case converted](https://github.com/zauberzeug/nicegui/blob/8a86d2064f8f4464f3819ac5c6763a2cb2d0e990/website/style.py#L31).

I'm also still in favour for using [tortoise ORM](https://tortoise.github.io/) in this example. The db access is quite low level and uses blocking io which is suboptimal. But we can do it once this PR is integrated.

2023-05-02 03:06 UTC, rodja commented
One other thing: do you think we can name the example "database"?

2023-05-02 03:58 UTC, godsarmy commented
> One other thing: do you think we can name the example "database"?

I still prefer to name it sqlite while i would like to provide another example in the future to use ORM to operate db named as  "database"

2023-05-02 05:24 UTC, rodja commented
> I still prefer to name it sqlite while i would like to provide another example in the future to use ORM to operate db named as "database"

Why would we need two examples? I would expect the ORM example to get simpler and simultaneously more production-ready than the  raw sqlite example...

2023-05-02 05:31 UTC, rodja commented on examples/sqlite/db/users.sql
Is this file needed?

2023-05-04 09:02 UTC, falkoschindler commented
I just reviewed the code and committed several small improvements:

- remove the unused db file
- add a .gitignore
- improve type annotation
- remove some expendable whitespace, comments, docstrings and exception handlers
- use more consistent function and variable names
- use `ui.number` consistently`
- fix initial `conn.commit()` not being called
- use `on_click` instead of `.on('click')`
- use `color` attribute instead of background color classes
- use notification type instead of color
- use global `dialog_id` variable instead of `get_id` label (still not perfect, but ok for this example)
- avoid using UI elements for passing around data, use `user` dictionary instead

Removing exception handling is certainly disputable. But I chose to cut some corners to shorten the example and to focus on the essence.

Using an ORM remains an open task.

2023-05-04 11:24 UTC, rodja approved these changes

2023-05-04 11:36 UTC, merged

2023-05-05 02:28 UTC, godsarmy commented
> I just reviewed the code and committed several small improvements:
> 
> * remove the unused db file
> * add a .gitignore
> * improve type annotation
> * remove some expendable whitespace, comments, docstrings and exception handlers
> * use more consistent function and variable names
> * use `ui.number` consistently
> * fix initial `conn.commit()` not being called
> * use `on_click` instead of `.on('click')`
> * use `color` attribute instead of background color classes
> * use notification type instead of color
> * use global `dialog_id` variable instead of `get_id` label (still not perfect, but ok for this example)
> * avoid using UI elements for passing around data, use `user` dictionary instead
> 
> Removing exception handling is certainly disputable. But I chose to cut some corners to shorten the example and to focus on the essence.
> 
> Using an ORM remains an open task.

HI Thank you for the change. I think the change makes sense. As a new new user for nicegui, i get to know the best practice. I will submit another PR to convert the example modeled in ORM.

2023-06-30 05:44 UTC, rodja commented
I finally reworked the [sqlite database example](https://github.com/zauberzeug/nicegui/blob/main/examples/sqlite_database/main.py) to use Tortoise ORM.