Auto complete input
zauberzeug/nicegui pull request #824
Opened 2023-04-24 05:28 UTC by phoskee

Correctly created the PR (I guess) and fixed the bug discussed on #818

2023-04-25 03:37 UTC, rodja requested changes
That is super cool. Could you also add a demo to [label_documentation.py](https://github.com/zauberzeug/nicegui/blob/main/website/more_documentation/label_documentation.py)? See [image_documentation.py](https://github.com/zauberzeug/nicegui/blob/main/website/more_documentation/image_documentation.py) for an example on how additional demos are placed on the documentation page.

2023-04-25 03:37 UTC, rodja commented on nicegui/elements/input.py
> +                if len(self.value) > 1:
Why do you only start autocompletion after the second character typed in?

2023-04-25 14:59 UTC, rodja commented on nicegui/elements/input.py
> +                if len(self.value) > 1:
Ok, without `if` is a bit too much. But I think `> 0` would be more intuitive. Take vscode autocompletion for example. It starts suggesting as soon as you start typing.

2023-04-25 15:00 UTC, rodja commented
> You meant input_documentation.py ?

Yes. Sorry for the mix up.

2023-04-26 03:34 UTC, rodja approved these changes

2023-04-26 03:34 UTC, rodja commented
Wonderful! Thank you so much for adding this.

2023-04-26 03:35 UTC, merged

2023-04-26 06:11 UTC, falkoschindler commented
I just reviewed and improved the code a little bit.

- To support Python 3.7, we need to use `List` instead of `list` for type annotations.
- When typing `tab` without any valid match, the input was reset to value `None`. I fixed it so that the current value is preserved in this case.

I'm still unsure about the `keydown.tab` event. Using `keydown.tab.prevent` feels a bit more natural (the focus stays on the input element), but prevents the user from tabbing out of the element to focus the next one.

2023-04-26 06:34 UTC, rodja commented
Ah yes. Maybe the merge was a bit early. Sorry about that. Could we maybe use `keydown.tab.prevent` and  jump to the next element if we do not have something to autocomplete?