added reload and time_stamp parameter to set_source method
zauberzeug/nicegui pull request #871
Opened 2023-05-01 16:01 UTC by melandur

Adding '?t=time.time()' to the source path to ensure a reload doesn't seem very python native.

I suggest adding the reload parameter, which inserts the latest time into the source to ensure a forced reload.
Also, an optional time_stamp parameter should be added for an custom reloading of the content.

The source path string + '?t=time.time()'  pattern is still possible by default

2023-05-01 17:32 UTC, rodja approved these changes
I like it a lot. Maybe we should make it the default? If you set the source you expect it to be updated, right? What is your take, @falkoschindler?

2023-05-01 17:33 UTC, rodja commented
If we change the behaviour it is something for 1.3. Or we apply the PR as it is and change the default behaviour in 1.3?

2023-05-02 13:11 UTC, falkoschindler requested changes
Although I like the initiative to make the hacky cache prevention more Pythonic, I have concerns with the current implementation:

1. Only `set_source` allows using the `reload` parameter. But `source = ...`, the initializer and binding won't offer such an option. This is ok, but feels a little incomplete.
2. Using `reload=True` changes `self.source` in an unpredictable way. So the following assertion fails and it's not obvius why:
    ```py
    image.set_source(src, reload=True)
    assert i.source == src
    ```
3. The implementation relies on `source` not containing an argument `t` - and that the API ignores an additional argument `t`. And technically it relies on `source` not containing _any_ arguments, since it appends a `?`. I think we should check for existing `?` and use a more robust parameter name like `_nicegui_t`.

To address points 1 and 2, I'd suggest to add an initializer parameter `prevent_cache: bool = False`. When setting the `src` prop based on the `source` value in `on_source_change`, we can add an additional URL parameter depending on `self.prevent_cache`, using `?` or `&` and a robust parameter name (see point 3).

2023-05-02 15:06 UTC, falkoschindler commented
I just experimented with the suggestion from [my comment above](https://github.com/zauberzeug/nicegui/pull/871#pullrequestreview-1409070813) and the following example:

```py
image = ui.image('https://picsum.photos/200/300', prevent_cache=True).classes('w-96')
ui.button('Click me', on_click=lambda: image.set_source('https://picsum.photos/200/300'))
```

I wanted the image to update on every button click. But since the source remains identical, `on_source_change` isn't called. So it isn't enough to update the timestamp there.

2023-07-16 15:08 UTC, falkoschindler commented
I'll close this PR because there are still unresolved problems with the proposed implementation and the discussion is stale for over a month now.
Feel free to re-open the discussion or post a new pull request if you want to continue discussing and working on this subject.

2023-07-16 15:08 UTC, closed without merging